// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB808A3iW6sl2a5okmlfVMc4dRAroa8OTY',
    appId: '1:410314028398:web:a324a3eae51d129050bd7f',
    messagingSenderId: '410314028398',
    projectId: 'pinyin-pal',
    authDomain: 'pinyin-pal.firebaseapp.com',
    storageBucket: 'pinyin-pal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChINWw8P9bhFCIip5fzCp23vK0Gi-7X-M',
    appId: '1:410314028398:android:e323d190a9d82b1950bd7f',
    messagingSenderId: '410314028398',
    projectId: 'pinyin-pal',
    storageBucket: 'pinyin-pal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZN4LwvFQMJLM1A-DoMQAjCuCAwDxrMz0',
    appId: '1:410314028398:ios:457da153dce1ddda50bd7f',
    messagingSenderId: '410314028398',
    projectId: 'pinyin-pal',
    storageBucket: 'pinyin-pal.appspot.com',
    iosClientId: '410314028398-c3sug68833tjvjbensr7cbihkjtkcq5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinyinPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZN4LwvFQMJLM1A-DoMQAjCuCAwDxrMz0',
    appId: '1:410314028398:ios:457da153dce1ddda50bd7f',
    messagingSenderId: '410314028398',
    projectId: 'pinyin-pal',
    storageBucket: 'pinyin-pal.appspot.com',
    iosClientId: '410314028398-c3sug68833tjvjbensr7cbihkjtkcq5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pinyinPal',
  );
}
